### PR TITLE
SEED/GBR-05 - OrgMixin Property endpoint revisions (depends on SEED/GBR-01, 02 & 03) -not ready for upstream

### PR DESCRIPTION
**Pull request by fablet**
#### Definition of Done:
- [ ] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [ ] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [ ] Does this PR require a regression test? All fixes require a regression test.
- [ ] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

### CODE REVIEW

**Comment by fablet** [comment]
One of the things I just discovered will need to be checked/fixed in the serializer is that the update_state and save methods were removed from the PropertyView model in the updates to the develop branch

**Comment by tallus** [comment]
On 03/24/2017 11:27 AM, Fable Turas wrote:
>
> One of the things I just discovered will need to be checked/fixed in 
> the serializer is that the update_state and save methods were removed 
> from the PropertyView model in the updates to the develop branch
>
Both of these were doing auto-logging: any idea what replaced them? 
(might be a post save trigger)

**Comment by fablet** [comment]
it looks like they started doing some work with the audit logs in relation to issue SEED-platform/seed#1139
I think that functionality may be occurring in the view now.

**Comment by tallus** [comment]
Please update with status re possible conflicts

**Comment by fablet** [comment]
I do not believe this one is ready to push upstream.  There is functionality in the upstream is implementing through their PropertyViewSet that is not fully handled by our PropertyViewSet.  I believed we talked about continuing to run our fork in parallel until that can be completely addressed.

**Pull request closed without merging**
